{% set name = "autoreject" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26e7e17fa57b78bad23d6e5a1b6eb8a4558fb6cb331953605f1ad9d7b085d3f5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy >=1.8
    - scipy >=0.16
    - mne-base >=0.14
    - scikit-learn >=0.18
    - joblib
    - matplotlib-base >=1.3
    - tqdm
    - h5py

test:
  imports:
    - autoreject
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://autoreject.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Automatically reject bad trials and repair bad sensors in M/EEG data.
  dev_url: https://github.com/autoreject/autoreject

extra:
  recipe-maintainers:
    - hoechenberger
